### ISSUE TITLE
Implement info-update event in wechaty

### ISSUE THREAD

**Issue by hcfw007** [juzibot/wechaty#15]
We do have a dirty event to invalid cache, however the bot also needs to listen to such events so that it can update external long-term storage such as database.
After some early thinking, I think we have 3 basic options here.
1. Expand the dirty event.

So far the dirty events stop propagation at wechaty level. If we can make it through out to bot level, the bot can use the payload (usually id) to load the new data and refresh database.
pros and cons: minum change to the current design. Dirty events fire frequently, may cause abundant I/O stress.

2. New event: 'Info-update'

We can create a new event which focus on this functionality. It can be very specefic. e.g.
```ts
export interface InfoUpdateEventPayload {
  type: string,
  id: string,
  field: string,
  oldValue?: string,
  newValue: string,
}
```
pros and cons: This event will fit our current need perfectly, we don't even have to sync and load payload again. However there is not much expansibility with this design. (maybe message info update? e.g. we can update the message sending status to failed after the callback since the deleted event comes later than message sending callback)

3. New event: 'System-Notification'

We can create a more flexible new event than the previous design. This is similar to system message in message event but with no coversation id. Possible scenario may include info modification, notifications (e.g. get banned by Tencent)and post events (we don't have initiative post event so far).
pros and cons: Just the opsit to the second design. Many stuff can be put into this event and it will be hard to write a clear tye definition.

Personally I like design 2.

**Comment by su-chang** [comment]
Vote 2

**Comment by hcfw007** [comment]
Merged
