### ISSUE TITLE
Support Moment Publish Options

### ISSUE THREAD

**Issue by hcfw007** [juzibot/wechaty#40]
Apporach 1: add an option when posting moment

wechaty level:
```ts
wechatyBot.publish(post: PostInterface, options?: MomentOptioins)

interface MomentOptioins {
  visibleList?: ContactInterface[]
  location?: Location
}

```

puppet level
```ts
abstract momentPublish(payload: PostPayload, options: PuppetMomentOptions)

interface PostOptioins {
  visibleList?: string[]
  location?: LocationPayload
}

```

Apporach 2: make visible list a part of post payload

wechaty-puppet:
```ts
interface PostPayloadBase {
  parentId? : string    // `undefined` means it's original
  rootId?   : string    // `undefined` means it's not a reply (original or repost)
  type?     : PostType

  location?: LocationPayload
  visibleList?: string[]
}
```

**Comment by windmemory** [comment]
I prefer the 2nd approach, I think the visibleList and location should be properties of the post.

**Comment by hcfw007** [comment]
> I prefer the 2nd approach, I think the visibleList and location should be properties of the post.

yeah originally I like the first one, but then it comes to me that after the post has been published, such info would be lost in wechaty level, and also we won't know these properties when one day we could view timeline in miaohui.

**Comment by windmemory** [comment]
> > I prefer the 2nd approach, I think the visibleList and location should be properties of the post.
> 
> yeah originally I liked the first one, but then it comes to me that after the post has been published, such info would be lost in wechaty level, and also we won't know these properties when one day we could view timeline in miaohui.

Okay, seems like we both agree to go with the 2nd solution, please go ahead implement it.
