### ISSUE TITLE
获取群成员的入群信息

### ISSUE THREAD

**Issue by su-chang** [juzibot/wechaty#43]
wechaty支持获取群成员入群时的基础信息

- 邀请人（inviterId）
- 入群时间（joinTime）
- 入群方式（joinScene）

由于目前 RoomMemberPayload 没有在wechaty中直接暴露，需要增加方法获取对应的信息。

```ts
interface RoomMemberJoinInfo {
  inviter: ContactInterface,
  joinScene: RoomMemberJoinScene,
  joinTime: Date,
}
```

```ts
async memberJoinInfo(contact: ContactInterface): Promise<RoomMemberJoinInfo>
```

**Comment by hcfw007** [comment]
我觉得可以，不过这样会引入额外的数据结构。
如果为每个属性提供单独的getter呢？

**Comment by su-chang** [comment]
> 如果为每个属性提供单独的getter呢？

但是 getter 不支持promise和传参。getter的promise可以用IIFE来搞。传参貌似没啥办法。

**Comment by hcfw007** [comment]
> IIFE

嗯，我的意思是广义的getter，每个属性提供一个方法来获取。

**Comment by su-chang** [comment]
OK 先用getter这样搞吧。

**Comment by su-chang** [comment]
相关PR列表
https://github.com/juzibot/wechaty-puppet/pull/33
https://github.com/juzibot/wechaty-puppet/pull/34
https://github.com/juzibot/wechaty-grpc/pull/30
https://github.com/juzibot/wechaty/pull/44
https://github.com/juzibot/wechaty-puppet-service/pull/33
https://github.com/juzibot/wechaty-puppet-workpro/pull/589
https://github.com/juzibot/wechaty-puppet-workpro/pull/600
